### ISSUE TITLE
[Suggestion] A Status Command

### ISSUE THREAD

**Issue by RichardB122** [Jo-Dan/The-Machine#2]
Hey,
After an hour or so of tinkering around and getting all the dependencies, I finally managed to get this running and it's pretty cool. An addition I thought would be neat is a "Status" command. 

Often in the show there is an info box that appears in the bottom and shows the status of something the machine is currently investigating or doing. It would be cool if when you typed "status" an infobox would appear in the bottom-left with information like how long the program has been running, how many subjects are in the frame, etc. The box could be toggleable when the command was run again.

**Comment by Jo-Dan** [comment]
That's an interesting idea. It should be pretty easy to implement.  I'll have a look when I get home tonight.

**Comment by Jo-Dan** [comment]
I've added a basic status box. You just need to download the new versions of the "machine.py" and "faceframes.py" files.

Use the "status" command to display the box (admin/analog) only.
I hope you like it :)

**Comment by RichardB122** [comment]
I tried it out, but it appears to be crashing because it can't find the "statusbox.tif" file. Is this just a renamed version of an existing file, or is it a new file you forgot to commit?

**Comment by Jo-Dan** [comment]
I'll commit the file tonight.

On 27 Jul 2016 8:06 AM, Jordan Peters <jhpeters98@hotmail.com> wrote:

Ah shit. I forgot to commit it :( . For now rename a copy of slim info box

On 27 Jul 2016 12:26 AM, RichardB122 <notifications@github.com> wrote:

I tried it out, but it appears to be crashing because it can't find the "statusbox.tif" file. Is this just a renamed version of an existing file, or is it a new file you forgot to commit?

**Comment by Jo-Dan** [comment]
Ah shit. I forgot to commit it :( . For now rename a copy of slim info box

**Comment by Jo-Dan** [comment]
Ok I've uploaded the statusbox.tif file now, sorry about that. At the moment it's just a slightly modified info box, I'm not sure if you had a specific style in mind.

**Comment by Jo-Dan** [comment]
Ok I've updated it with a new box closer to the style of the status boxes in the show (namely the one the machine uses to display the status of Samaritan
![Screen cap from show](https://cloud.githubusercontent.com/assets/17822268/17247278/7eadd0d6-55d5-11e6-94ae-944f3ea9fe3e.png)). I'll close this issue if you are happy with it, otherwise feel free to give more suggestions.

**Comment by Jo-Dan** [comment]
Ok I've updated it with a new box closer to the style of the status boxes in the show (namely the one the machine uses to display the status of Samaritan
![Screen cap from show](https://cloud.githubusercontent.com/assets/17822268/17247278/7eadd0d6-55d5-11e6-94ae-944f3ea9fe3e.png)). 
You'll just need to redownload faceframes.py, machine.py and the new gui/machine/statusbox_new file.
I'll close this issue if you are happy with it, otherwise feel free to give more suggestions.
