### ISSUE TITLE
Python DLL 

### ISSUE THREAD

**Issue by connor-nichols** [Jo-Dan/The-Machine#5]
I'm getting the python DLL error: code 14001 and I have OpenCV, what should I do?

**Comment by Jo-Dan** [comment]
Did you install AV bin?

**Comment by connor-nichols** [comment]
I'm trying but it says "Error creating C:\Program Files\AVBin\AVBin-bin10-win64-uninstaller.exe"

**Comment by Jo-Dan** [comment]
Hmm. That's an issue with avbin Sorry. I wouldn't know how to fix it. Are you installing as administrator?

**Comment by connor-nichols** [comment]
Yes

**Comment by Jo-Dan** [comment]
Sorry man I can't really help then. Not only did I have no issues personally but I haven't been on my computer for 4 months and won't be on it again for another 4 because I'm on my gap year. 

If youre installing the proper avbin and everything and it's not working you may need to perform some google Fu or post something on the avbin GitHub. Or maybe stackexchange.
